[package]
name = "prog-integer-parse"
version = "0.1.0"
authors = ["MinusGix <minusgix@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# For being able to be generic over integers.
num-traits = "0.2.14"
